### ISSUE TITLE
Java error on the latest version of Folia

### ISSUE THREAD

**Issue by FreddieDK** [TheNextLvl-net/tweaks#4]
java.lang.UnsupportedClassVersionError: net/thenextlvl/tweaks/TweaksPlugin has been compiled by a more recent version of the Java Runtime (class file version 63.0), this version of the Java Runtime only recognizes class file versions up to 61.0

Using Java 17, folia 1.20.4

**Comment by FreddieDK** [comment]
[16:46:03 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'tweaks-2.0.7-all (1).jar' in folder 'plugins'
java.lang.UnsupportedClassVersionError: net/thenextlvl/tweaks/TweaksPlugin has been compiled by a more recent version of the Java Runtime (class file version 63.0), this version of the Java Runtime only recognizes class file versions up to 61.0
        at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
        at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
        at io.papermc.paper.plugin.entrypoint.classloader.PaperSimplePluginClassLoader.findClass(PaperSimplePluginClassLoader.java:103) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:114) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.plugin.entrypoint.classloader.PaperPluginClassLoader.loadClass(PaperPluginClassLoader.java:103) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:467) ~[?:?]
        at io.papermc.paper.plugin.provider.util.ProviderUtil.loadClass(ProviderUtil.java:51) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.util.ProviderUtil.loadClass(ProviderUtil.java:29) ~[folia-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.provider.type.paper.PaperPluginParent$PaperServerPluginProvider.createInstance(PaperPluginParent.java:169) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.plugin.provider.type.paper.PaperPluginParent$PaperServerPluginProvider.createInstance(PaperPluginParent.java:139) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:36) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.loadPlugins(CraftServer.java:513) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[folia-1.20.4.jar:git-Folia-"e97b1ee"]

**Comment by NonSwag** [comment]
Tweaks is based on java 19
compiling Folia using java 19 or newer will fix this issue
